package com.adsamcik.riposte.feature.import_feature.data

import com.adsamcik.riposte.core.model.MemeMetadata
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import com.google.common.truth.Truth.assertThat
import org.junit.Test

/**
 * Integration tests for CLI-generated JSON sidecar compatibility.
 *
 * These tests verify that the JSON sidecar files generated by the riposte-cli
 * Python tool can be correctly parsed by the Kotlin MemeMetadata class.
 *
 * Note: Tests for ZipImporter.extractBundle require Robolectric or Android
 * instrumentation tests due to Uri.fromFile() dependencies.
 */
class ZipImporterTest {
    private val json = Json { ignoreUnknownKeys = true }

    // ==================== CLI Output Compatibility Tests ====================

    @Test
    fun `parseMetadataJson handles minimal CLI output`() {
        // Minimal output from CLI: just emojis and required fields
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂"],
                "createdAt": "2026-01-25T12:00:00+00:00",
                "appVersion": "cli-1.0.0"
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.schemaVersion).isEqualTo("1.0")
        assertThat(metadata.emojis).isEqualTo(listOf("😂"))
        assertThat(metadata.createdAt).isEqualTo("2026-01-25T12:00:00+00:00")
        assertThat(metadata.appVersion).isEqualTo("cli-1.0.0")
    }

    @Test
    fun `parseMetadataJson handles full CLI output`() {
        // Full output from CLI with all fields populated
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["👾", "🎮", "😎", "🕹️"],
                "createdAt": "2026-01-25T07:52:01.265630+00:00",
                "appVersion": "cli-1.0.0",
                "title": "Ultimate Gamer Vibes",
                "description": "A person in a gaming room wearing retro Space Invader-themed gear",
                "tags": ["gaming", "space invaders", "retro", "arcade", "funny"],
                "textContent": "Game Over"
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.schemaVersion).isEqualTo("1.0")
        assertThat(metadata.emojis).isEqualTo(listOf("👾", "🎮", "😎", "🕹️"))
        assertThat(metadata.title).isEqualTo("Ultimate Gamer Vibes")
        assertThat(metadata.description).isEqualTo(
            "A person in a gaming room wearing retro Space Invader-themed gear",
        )
        assertThat(metadata.tags).isEqualTo(listOf("gaming", "space invaders", "retro", "arcade", "funny"))
        assertThat(metadata.textContent).isEqualTo("Game Over")
    }

    @Test
    fun `parseMetadataJson handles Unicode emojis`() {
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂", "🔥", "👾", "❤️", "🏳️‍🌈", "👨‍💻"]
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.emojis).hasSize(6)
        assertThat(metadata.emojis).contains("😂")
        assertThat(metadata.emojis).contains("🔥")
        assertThat(metadata.emojis).contains("👾")
        assertThat(metadata.emojis).contains("❤️")
        // ZWJ sequences
        assertThat(metadata.emojis).contains("🏳️‍🌈")
        assertThat(metadata.emojis).contains("👨‍💻")
    }

    @Test
    fun `parseMetadataJson handles Unicode text content`() {
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂"],
                "title": "日本語タイトル",
                "description": "Описание на русском 中文描述",
                "textContent": "مرحبا بالعالم"
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.title).isEqualTo("日本語タイトル")
        assertThat(metadata.description).isEqualTo("Описание на русском 中文描述")
        assertThat(metadata.textContent).isEqualTo("مرحبا بالعالم")
    }

    @Test
    fun `parseMetadataJson ignores unknown fields`() {
        // CLI might add new fields in future versions
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂"],
                "unknownField": "should be ignored",
                "anotherNewField": 123
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.schemaVersion).isEqualTo("1.0")
        assertThat(metadata.emojis).isEqualTo(listOf("😂"))
    }

    @Test
    fun `parseMetadataJson handles empty tags list`() {
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂"],
                "tags": []
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.tags).isEmpty()
    }

    @Test
    fun `parseMetadataJson handles missing optional fields`() {
        val cliOutput =
            """
            {
                "schemaVersion": "1.0",
                "emojis": ["😂"]
            }
            """.trimIndent()

        val metadata = json.decodeFromString<MemeMetadata>(cliOutput)

        assertThat(metadata.schemaVersion).isEqualTo("1.0")
        assertThat(metadata.emojis).isEqualTo(listOf("😂"))
        assertThat(metadata.title).isNull()
        assertThat(metadata.description).isNull()
        assertThat(metadata.textContent).isNull()
        assertThat(metadata.createdAt).isNull()
        assertThat(metadata.appVersion).isNull()
        assertThat(metadata.tags).isEmpty()
    }

    @Test
    fun `metadata round trip serialization works`() {
        // Create metadata as CLI would
        val original =
            MemeMetadata(
                schemaVersion = "1.0",
                emojis = listOf("😂", "🔥", "💯"),
                title = "Test Meme",
                description = "A funny meme",
                createdAt = "2026-01-25T12:00:00+00:00",
                appVersion = "cli-1.0.0",
                tags = listOf("funny", "test"),
                textContent = "Hello World",
            )

        // Serialize as CLI does
        val jsonString = json.encodeToString(original)

        // Parse as Android app does
        val parsed = json.decodeFromString<MemeMetadata>(jsonString)

        assertThat(parsed.schemaVersion).isEqualTo(original.schemaVersion)
        assertThat(parsed.emojis).isEqualTo(original.emojis)
        assertThat(parsed.title).isEqualTo(original.title)
        assertThat(parsed.description).isEqualTo(original.description)
        assertThat(parsed.createdAt).isEqualTo(original.createdAt)
        assertThat(parsed.appVersion).isEqualTo(original.appVersion)
        assertThat(parsed.tags).isEqualTo(original.tags)
        assertThat(parsed.textContent).isEqualTo(original.textContent)
    }

    @Test
    fun `toEmojiTags converts emojis correctly`() {
        val metadata = MemeMetadata(emojis = listOf("😂", "🔥"))

        val emojiTags = metadata.toEmojiTags()

        assertThat(emojiTags).hasSize(2)
        assertThat(emojiTags[0].emoji).isEqualTo("😂")
        assertThat(emojiTags[1].emoji).isEqualTo("🔥")
    }

}
